language: c
sudo: false
dist: xenial
addons:
  apt:
    packages:
      - nasm
      - diffutils
compiler:
  - gcc
cache:
  directories:
    - ffmpeg-samples
before_install:
  - sudo apt-get install libglew-dev libglfw3-dev
script:
  - mkdir -p ffmpeg-samples
  - ./configure --samples=ffmpeg-samples --cc=$CC --enable-libx264 --enable-gpl --enable-opengl --extra-libs='-lGLEW -lEGL'
  - make -j 8
  - make fate-rsync
  - make check -j 8
