language: c
sudo: false
addons:
  apt:
    packages:
      - nasm
      - diffutils
compiler:
  - gcc
cache:
  directories:
    - ffmpeg-samples
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install nasm; fi
script:
  - mkdir -p ffmpeg-samples
  - ./configure --samples=ffmpeg-samples --cc=$CC --enable-gpl --enable-opengl --extra-libs='-lGLEW -lglfw' --enable-filter=gltransition --disable-shared --enable-static
  - make -j 8
  - make fate-rsync
  - make check -j 8
