language: c
sudo: false
dist: xenial
addons:
  apt:
    packages:
      - nasm
      - diffutils
      - libglew-dev
compiler:
  - gcc
cache:
  directories:
    - ffmpeg-samples
before_install:
  - sudo apt-get install libglfw3-dev
script:
  - mkdir -p ffmpeg-samples
  - ./configure --samples=ffmpeg-samples --cc=$CC
  - make -j 8
  - make fate-rsync
  - make check -j 8
