language: c
sudo: false
addons:
  apt:
    packages:
      - nasm
      - diffutils
compiler:
  - gcc
cache:
  directories:
    - ffmpeg-samples
script:
  - mkdir -p ffmpeg-samples
  - ./configure --samples=ffmpeg-samples --cc=$CC --enable-gpl --enable-opengl --extra-libs='-lGLEW -lglfw' --enable-filter=gltransition --disable-shared --enable-static
  - make -j 8
  - make fate-rsync
  - make check -j 8
