language: c
sudo: false
dist: xenial
addons:
  apt:
    packages:
      - nasm
      - diffutils
      - libglew-dev
      - libglfw3-dev
compiler:
  - gcc
cache:
  directories:
    - ffmpeg-samples
script:
  - mkdir -p ffmpeg-samples
  - ./configure --samples=ffmpeg-samples --cc=$CC
  - make -j 8
  - make fate-rsync
  - make check -j 8
